config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :artists

  root 'artists#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    keyword = params['keyword'].present? ? params['keyword'].gsub(/\s+/, '+') : 'Indonesia'
    @keyword = params['keyword'].present? ? params['keyword'].gsub(/\s+/, '+') : nil
    @page = params['page'].present? ? params['page'].to_i : 1

    # Get result from API last.fm
    results = JSON.parse(RestClient.get("http://ws.audioscrobbler.com/2.0/?method=geo.gettopartists&country=#{keyword}&api_key=635f92c583abcf3404dd1377219306e9&limit=5&page=#{@page}&format=json"))
    if results["error"].present?
      flash[:alert] = "country name invalid or not listed"
      redirect_to root_path
    else
      @top_artist = results["topartists"]["artist"]
      @values = WillPaginate::Collection.create(@page, 5,  results["topartists"]["@attr"]["totalPages"]) do |pager|
        pager.replace @top_artist
      end
    end

  end

  def show
    @name = params[:id]
    # Get result from API last.fm
    results = JSON.parse(RestClient.get("http://ws.audioscrobbler.com/2.0/?method=artist.gettoptracks&artist=#{@name}&api_key=635f92c583abcf3404dd1377219306e9&format=json"))
    @top_tracks = results["toptracks"]["track"]

    # render component: 'Table', props: { top_tracks: @top_tracks }, tag: 'span', class: 'todo'

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/index.html.erb
<div class="container">
  <div class="popular">
    <div class="col-md-12">
      <div class="row ">
        <div class="col-md-6 align-self-center"> <h2 class="title">THE MOST POPULAR ARTIST  <%= @keyword.present? ? "IN #{@keyword.upcase}" : ''%></h2> </div>
      </div>
      <% flash.each do |key, value| %>
        <div class="alert alert-danger" role="alert">
          <%= content_tag :div, value, class: "flash #{key}" %>
        </div>
      <% end %>
      <%= form_tag(root_path, method: :get) do %>

        <div class="col-md-8">

          <div class="row">
            <div class="col-md-7">
              <%=text_field_tag 'keyword', @keyword, placeholder:'Enter Country Name', class: "form-control mb-2 mb-sm-0"%>
            </div>
            <div class="col-md-1"><%= submit_tag 'Search',class: "btn btn-primary" %></div>
          </div>
        </div>
      <% end %>
    </div>
    &nbsp;
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Band Name</th>
          <th>Picture</th>
        </tr>
      </thead>
      <tbody>
        <% @top_artist.each do |artist|%>
          <tr>
            <td>
              <%= link_to artist_path(id: artist["name"]), target: :_blank do %>
                <%=artist["name"]%>
              <%end%>
            </td>
            <td>
              <%= link_to artist_path(id: artist["name"]), target: :_blank do %>
                <%=image_tag artist["image"][1]["#text"]%>
              <%end%>

            </td>
          </tr>
        <%end%>
      </tbody>

    </table>

    <%= will_paginate @values, params: { keyword: @keyword }, renderer: BootstrapPagination::Rails %>
  </div>
</div>

app/views/artists/show.html.erb
<div class="container">
  <div class="popular">
    <h2 class="title">TOP TRACKS OF <%=@name%></h2>

    <%= react_component("Table", { top_tracks: @top_tracks }, {prerender: true}) %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lastfm</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/react-bootstrap-table/4.3.1/react-bootstrap-table.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>